### ISSUE TITLE
Fix alembic `Import error: cannot import name db`

### ISSUE THREAD

**Issue by CloudNiner** [azavea/ashlar#8]
Broken by `from ashlar import db` in https://github.com/azavea/ashlar/commit/5ac7a68bdb73ee3115da0c14163d1ab85c913b47

**Comment by CloudNiner** [comment]
Closing. No longer using alembic.
